server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # This routes all unknown requests to index.html for React/Vue SPA routing
    location / {
        try_files $uri $uri/ /index.html;
    }
}
