services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fullstack-backend
    env_file:
      - ./backend/.env
    environment:
      FASTAPI_EMBEDDING_URL: http://access_hub-qdrant_api-1:8000/embedding_AMS
      FASTAPI_EMBEDDING_URL_VMS: http://access_hub-qdrant_api-1:8000/embedding
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - core_net
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: fullstack-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - core_net
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: access_hub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - core_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d access_hub"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - core_net
    restart: unless-stopped


volumes:
  pgdata:

networks:
  core_net:
    name: core_net
