"""Added visitor_history_details table

Revision ID: 15700c19b73a
Revises: b33c9a1d2f3
Create Date: 2026-02-23 17:22:56.022929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15700c19b73a'
down_revision = 'b33c9a1d2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_change_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('attendance_record_id', sa.String(length=36), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('requested_changes', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_change_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_change_requests_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_change_requests_request_date'), ['request_date'], unique=False)

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_modified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('modified_by_request_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'attendance_change_requests', ['modified_by_request_id'], ['id'])

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_type', sa.String(length=20), nullable=True))

    with op.batch_alter_table('lpr_hotlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_lpr_hotlist_organization_id'))
        batch_op.drop_index(batch_op.f('idx_lpr_hotlist_vehicle_number'))
        batch_op.create_index(batch_op.f('ix_lpr_hotlist_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lpr_hotlist_vehicle_number'), ['vehicle_number'], unique=False)

    with op.batch_alter_table('lpr_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_lpr_logs_organization_id'))
        batch_op.drop_index(batch_op.f('idx_lpr_logs_timestamp'))
        batch_op.drop_index(batch_op.f('idx_lpr_logs_vehicle_number'))
        batch_op.create_index(batch_op.f('ix_lpr_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lpr_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_lpr_logs_vehicle_number'), ['vehicle_number'], unique=False)

    with op.batch_alter_table('lpr_whitelist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_lpr_whitelist_organization_id'))
        batch_op.drop_index(batch_op.f('idx_lpr_whitelist_vehicle_number'))
        batch_op.create_index(batch_op.f('ix_lpr_whitelist_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lpr_whitelist_vehicle_number'), ['vehicle_number'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('subscription_plan',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'free'::character varying"))

    with op.batch_alter_table('visitor_history_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('duration_from', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('duration_to', sa.Float(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_visitor_history_details_adhar_number'))
        batch_op.create_index(batch_op.f('ix_visitor_history_details_visitor_id'), ['visitor_id'], unique=False)
        batch_op.create_foreign_key(None, 'visitors', ['visitor_id'], ['id'])
        batch_op.drop_column('duration')
        batch_op.drop_column('adhar_number')

    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.alter_column('visitor_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'guest'::character varying"))
        batch_op.create_unique_constraint(None, ['badge_number'])
        batch_op.create_foreign_key(None, 'group_visits', ['group_visit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('visitor_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'guest'::character varying"))

    with op.batch_alter_table('visitor_history_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adhar_number', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_visitor_history_details_visitor_id'))
        batch_op.create_index(batch_op.f('ix_visitor_history_details_adhar_number'), ['adhar_number'], unique=False)
        batch_op.drop_column('duration_to')
        batch_op.drop_column('duration_from')
        batch_op.drop_column('visitor_id')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('subscription_plan',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'free'::character varying"))

    with op.batch_alter_table('lpr_whitelist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lpr_whitelist_vehicle_number'))
        batch_op.drop_index(batch_op.f('ix_lpr_whitelist_organization_id'))
        batch_op.create_index(batch_op.f('idx_lpr_whitelist_vehicle_number'), ['vehicle_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_lpr_whitelist_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('lpr_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lpr_logs_vehicle_number'))
        batch_op.drop_index(batch_op.f('ix_lpr_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_lpr_logs_organization_id'))
        batch_op.create_index(batch_op.f('idx_lpr_logs_vehicle_number'), ['vehicle_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_lpr_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('idx_lpr_logs_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('lpr_hotlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lpr_hotlist_vehicle_number'))
        batch_op.drop_index(batch_op.f('ix_lpr_hotlist_organization_id'))
        batch_op.create_index(batch_op.f('idx_lpr_hotlist_vehicle_number'), ['vehicle_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_lpr_hotlist_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_column('duration_type')

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('modified_by_request_id')
        batch_op.drop_column('is_modified')

    with op.batch_alter_table('attendance_change_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_change_requests_request_date'))
        batch_op.drop_index(batch_op.f('ix_attendance_change_requests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_change_requests_employee_id'))

    op.drop_table('attendance_change_requests')
    # ### end Alembic commands ###
