"""remove unwanted visitor tables

Revision ID: 1d77237eb82d
Revises: 7a9ce6c843ac
Create Date: 2026-02-24 12:44:54.261902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d77237eb82d'
down_revision = '7a9ce6c843ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vip_visitor_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vip_visitor_preferences_organization_id'))
        batch_op.drop_index(batch_op.f('ix_vip_visitor_preferences_visitor_id'))

    op.drop_table('vip_visitor_preferences')
    with op.batch_alter_table('visitor_health_screenings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_health_screenings_organization_id'))
        batch_op.drop_index(batch_op.f('ix_visitor_health_screenings_visitor_id'))

    op.drop_table('visitor_health_screenings')
    with op.batch_alter_table('visitor_pre_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_pre_registrations_organization_id'))

    op.drop_table('visitor_pre_registrations')
    with op.batch_alter_table('visitor_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_documents_organization_id'))
        batch_op.drop_index(batch_op.f('ix_visitor_documents_visitor_id'))

    op.drop_table('visitor_documents')
    with op.batch_alter_table('visitor_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_badges_organization_id'))
        batch_op.drop_index(batch_op.f('ix_visitor_badges_visitor_id'))

    op.drop_table('visitor_badges')
    with op.batch_alter_table('delivery_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_logs_visitor_id'))

    op.drop_table('delivery_logs')
    with op.batch_alter_table('visitor_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_blacklist_email'))
        batch_op.drop_index(batch_op.f('ix_visitor_blacklist_id_proof_number'))
        batch_op.drop_index(batch_op.f('ix_visitor_blacklist_organization_id'))
        batch_op.drop_index(batch_op.f('ix_visitor_blacklist_phone_number'))

    op.drop_table('visitor_blacklist')
    with op.batch_alter_table('contractor_time_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contractor_time_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_contractor_time_logs_visitor_id'))

    op.drop_table('contractor_time_logs')
    with op.batch_alter_table('group_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_visits_organization_id'))

    op.drop_table('group_visits')
    with op.batch_alter_table('visitor_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_assets_visitor_id'))

    op.drop_table('visitor_assets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_assets',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('visitor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('asset_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('serial_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('security_seal_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('entry_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('exit_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('entry_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('exit_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('visitor_assets_visitor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('visitor_assets_pkey'))
    )
    with op.batch_alter_table('visitor_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_assets_visitor_id'), ['visitor_id'], unique=False)

    op.create_table('group_visits',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('group_leader_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('group_leader_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('purpose', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('scheduled_arrival', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expected_duration_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('group_visits_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('group_visits_pkey'))
    )
    with op.batch_alter_table('group_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_visits_organization_id'), ['organization_id'], unique=False)

    op.create_table('contractor_time_logs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('visitor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('clock_in_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('clock_out_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('billable_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('work_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('work_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('proof_of_work', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('contractor_time_logs_organization_id_fkey')),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('contractor_time_logs_visitor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('contractor_time_logs_pkey'))
    )
    with op.batch_alter_table('contractor_time_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contractor_time_logs_visitor_id'), ['visitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contractor_time_logs_organization_id'), ['organization_id'], unique=False)

    op.create_table('visitor_blacklist',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id_proof_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('visitor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('watchlist_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('added_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('visitor_blacklist_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('visitor_blacklist_pkey'))
    )
    with op.batch_alter_table('visitor_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_blacklist_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_blacklist_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_blacklist_id_proof_number'), ['id_proof_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_blacklist_email'), ['email'], unique=False)

    op.create_table('delivery_logs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('visitor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('package_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('package_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('delivery_photo_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('recipient_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('recipient_signature', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('delivery_logs_organization_id_fkey')),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('delivery_logs_visitor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('delivery_logs_pkey'))
    )
    with op.batch_alter_table('delivery_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_logs_visitor_id'), ['visitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_logs_organization_id'), ['organization_id'], unique=False)

    op.create_table('visitor_badges',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('visitor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('badge_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('badge_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('qr_code_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('issued_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('returned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('access_permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('visitor_badges_organization_id_fkey')),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('visitor_badges_visitor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('visitor_badges_pkey')),
    sa.UniqueConstraint('badge_number', name=op.f('visitor_badges_badge_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('visitor_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_badges_visitor_id'), ['visitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_badges_organization_id'), ['organization_id'], unique=False)

    op.create_table('visitor_documents',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('visitor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('document_template_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('signature_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('pdf_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('visitor_documents_organization_id_fkey')),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('visitor_documents_visitor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('visitor_documents_pkey'))
    )
    with op.batch_alter_table('visitor_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_documents_visitor_id'), ['visitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_documents_organization_id'), ['organization_id'], unique=False)

    op.create_table('visitor_pre_registrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('visitor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('purpose_of_visit', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('host_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('host_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('scheduled_arrival_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('scheduled_departure_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('qr_code', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('visitor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('visitor_pre_registrations_organization_id_fkey')),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('visitor_pre_registrations_visitor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('visitor_pre_registrations_pkey'))
    )
    with op.batch_alter_table('visitor_pre_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_pre_registrations_organization_id'), ['organization_id'], unique=False)

    op.create_table('visitor_health_screenings',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('visitor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('questionnaire_responses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('vaccination_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('vaccination_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('result', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('screener_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('screened_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('screened_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('visitor_health_screenings_organization_id_fkey')),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('visitor_health_screenings_visitor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('visitor_health_screenings_pkey'))
    )
    with op.batch_alter_table('visitor_health_screenings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_health_screenings_visitor_id'), ['visitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_health_screenings_organization_id'), ['organization_id'], unique=False)

    op.create_table('vip_visitor_preferences',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('visitor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('vip_tier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('preferred_greeting', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('dietary_requirements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accessibility_requirements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('other_preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('room_preparation_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('previous_visit_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('vip_visitor_preferences_organization_id_fkey')),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('vip_visitor_preferences_visitor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vip_visitor_preferences_pkey'))
    )
    with op.batch_alter_table('vip_visitor_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vip_visitor_preferences_visitor_id'), ['visitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vip_visitor_preferences_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###
