"""add visit_metadata column to visitor history

Revision ID: 3154dcc9d44f
Revises: 1d77237eb82d
Create Date: 2026-02-24 13:01:35.785888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3154dcc9d44f'
down_revision = '1d77237eb82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_history_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_history_details', schema=None) as batch_op:
        batch_op.drop_column('visit_metadata')

    # ### end Alembic commands ###
