"""simplify visitor schema

Revision ID: 7a9ce6c843ac
Revises: 15700c19b73a
Create Date: 2026-02-24 12:29:38.456919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a9ce6c843ac'
down_revision = '15700c19b73a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_history_details',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('visitor_id', sa.String(length=36), nullable=False),
    sa.Column('visitor_type', sa.String(length=50), nullable=True),
    sa.Column('host_name', sa.String(length=255), nullable=True),
    sa.Column('host_number', sa.String(length=20), nullable=True),
    sa.Column('purpose_of_visit', sa.String(length=500), nullable=False),
    sa.Column('allowed_floor', sa.String(length=100), nullable=False),
    sa.Column('allowed_tower', sa.String(length=100), nullable=True),
    sa.Column('duration_date_from', sa.DateTime(), nullable=True),
    sa.Column('duration_date_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visitor_history_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_history_details_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_history_details_visitor_id'), ['visitor_id'], unique=False)

    with op.batch_alter_table('visitor_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_alerts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_visitor_alerts_visitor_id'))

    op.drop_table('visitor_alerts')
    with op.batch_alter_table('visitor_movement_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_movement_logs_visitor_id'))

    op.drop_table('visitor_movement_logs')
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))
        batch_op.drop_constraint(batch_op.f('visitors_badge_number_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('visitors_group_visit_id_fkey'), type_='foreignkey')
        batch_op.drop_column('work_completed_proof')
        batch_op.drop_column('badge_number')
        batch_op.drop_column('group_visit_id')
        batch_op.drop_column('is_checked_in')
        batch_op.drop_column('current_floor')
        batch_op.drop_column('vehicle_type')
        batch_op.drop_column('feedback_comments')
        batch_op.drop_column('id_proof_image_path')
        batch_op.drop_column('company_address')
        batch_op.drop_column('check_in_time')
        batch_op.drop_column('expected_duration_hours')
        batch_op.drop_column('vehicle_check_status')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('special_instructions')
        batch_op.drop_column('company_name')
        batch_op.drop_column('host_phone')
        batch_op.drop_column('health_declaration_status')
        batch_op.drop_column('vehicle_model')
        batch_op.drop_column('pre_registration_status')
        batch_op.drop_column('id_proof_type')
        batch_op.drop_column('last_visit_date')
        batch_op.drop_column('check_out_time')
        batch_op.drop_column('material_declaration')
        batch_op.drop_column('delivery_package_count')
        batch_op.drop_column('allowed_floor')
        batch_op.drop_column('badge_status')
        batch_op.drop_column('temperature')
        batch_op.drop_column('vaccination_verified')
        batch_op.drop_column('host_name')
        batch_op.drop_column('nda_signed')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('parking_slot')
        batch_op.drop_column('created_at')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('is_recurring')
        batch_op.drop_column('vehicle_security_check_notes')
        batch_op.drop_column('nda_signed_at')
        batch_op.drop_column('delivery_recipient_name')
        batch_op.drop_column('photo_path')
        batch_op.drop_column('assets_carried')
        batch_op.drop_column('scheduled_departure_time')
        batch_op.drop_column('vehicle_number')
        batch_op.drop_column('actual_duration_hours')
        batch_op.drop_column('is_vip')
        batch_op.drop_column('badge_printed_at')
        batch_op.drop_column('is_pre_registered')
        batch_op.drop_column('id_proof_number')
        batch_op.drop_column('visitor_type')
        batch_op.drop_column('purpose_of_visit')
        batch_op.drop_column('visit_frequency')
        batch_op.drop_column('vehicle_photos')
        batch_op.drop_column('scheduled_arrival_time')
        batch_op.drop_column('feedback_rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_rating', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('scheduled_arrival_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_photos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('visit_frequency', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('purpose_of_visit', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('visitor_type', sa.VARCHAR(length=50), server_default=sa.text("'guest'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_proof_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_pre_registered', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('badge_printed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_vip', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('actual_duration_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('scheduled_departure_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('assets_carried', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('photo_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('delivery_recipient_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nda_signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_security_check_notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_recurring', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('parking_slot', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nda_signed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('host_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vaccination_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('badge_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('allowed_floor', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('delivery_package_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('material_declaration', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('check_out_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_visit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_proof_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pre_registration_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('health_declaration_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('host_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('special_instructions', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('vehicle_check_status', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('expected_duration_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('check_in_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('company_address', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_proof_image_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('feedback_comments', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_floor', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_checked_in', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('group_visit_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('badge_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('work_completed_proof', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('visitors_group_visit_id_fkey'), 'group_visits', ['group_visit_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('visitors_badge_number_key'), ['badge_number'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('gender')

    op.create_table('visitor_movement_logs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('visitor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('floor', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entry_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('exit_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('visitor_movement_logs_visitor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('visitor_movement_logs_pkey'))
    )
    with op.batch_alter_table('visitor_movement_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_movement_logs_visitor_id'), ['visitor_id'], unique=False)

    op.create_table('visitor_alerts',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('visitor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('current_floor', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('allowed_floor', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('alert_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('acknowledged', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('visitor_alerts_organization_id_fkey')),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('visitor_alerts_visitor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('visitor_alerts_pkey'))
    )
    with op.batch_alter_table('visitor_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_alerts_visitor_id'), ['visitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_alerts_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('visitor_history_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_history_details_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_visitor_history_details_organization_id'))

    op.drop_table('visitor_history_details')
    # ### end Alembic commands ###
